CC=CL
FLAGS=/c /Ox

main: MLVWriter MLVReader MLVFrameUtils
	LIB lib/*.obj /OUT:lib/libmlv.lib
	LINK /DLL lib/*.obj /OUT:lib/libmlv.dll

MLVWriter:
	$(CC) src/MLVWriter.c $(FLAGS) /Fo:lib/MLVWriter.obj

MLVReader:
	$(CC) src/MLVReader.c $(FLAGS) /Fo:lib/MLVReader.obj

MLVFrameUtils:
	$(CC) src/MLVFrameUtils.c $(FLAGS) /Fo:lib/MLVFrameUtils.obj